### ISSUE TITLE
button clicks on iOS

### ISSUE THREAD

**Issue by mmazloum** [Urigo/Ionic2-MeteorCLI-WhatsApp#6]
When build my app for iOS I encounter click problems, i need "sometimes" (its doesn't seem to be conditioned by a type of ionic 2 component) to click several times on a button to have the click detected. sometimes long press even activates the copy paste ios features on the button text

I wonder if any one knows the difference between Ionic 2 iOS compilator and Meteor iOS compilator because I have another iOS 10 app on Ionic 2 latest rc without Meteor which doesn't have this click problem ?

**Comment by Urigo** [comment]
@DAB0mB that sounds like the problem we encountered on Ionic 1.0 no?

**Comment by DAB0mB** [comment]
@Urigo Thats how it seems like.

@mmazloum If you're an iOS user you might encounter some issues related to double tapping not being submitted correctly. This is caused due to a package automatically included by `Metoer` and it is called `mobile-experience` so we can have a more native feeling for our app once running on a mobile device, which is not always right across the board. This package is simply a cluster of the following packages:
- `fastclick` - Avoid the 300ms touch delay.
- `mobile-status-bar` - Avoid the status bar information covering up your app content.
- `launch-screen` - Cover the app with a launch image so that people don’t have to see things loading.

You can already figure out that the `fastclick` is a potential basis for our issue. So we will install the same packages `mobile-experience` provides us with, with an exception of `fastclick`:

```
$ meteor add mobile-status-bar
$ meteor add launch-screen
```

**Comment by mmazloum** [comment]
@Urigo @DAB0mB this did the trick ! thanks a lot, in fact the real problem was that I always had to double click, removing fastclick package solved the issue.
