### ISSUE TITLE
meteor npm vs npm

### ISSUE THREAD

**Issue by tafelito** [Urigo/Ionic2-MeteorCLI-WhatsApp#8]
Hi guys, I have a question regarding the Whatsapp tutorial with meteor CLI. Is there any reason you are using npm instead of meteor npm for this tutorial? I followed the full app tutorial and everything is done using meteor npm. I've used meteor npm without problem until I got to the step where I have to do `typings install --save --global dt~moment`  and I couldn't get past that. I know thats just for the typings for moment package, but how do you do that within meteor CLI? 

Thank you

**Comment by dotansimha** [comment]
It's preferred to use `meteor npm install` because that makes sure that you use the correct version of Node (which bundled inside Meteor), and not your machine's because that can be an older version. 

When you want to install a global module (`-g`, like `typings`), always use `npm install` because it needs to install it to your machine's node installation and not into the Meteor's one, and you run it without Meteor CLI.

**Comment by tafelito** [comment]
OK thanks. The tutorial uses npm without meteor, that's why my confusion.

**Comment by dotansimha** [comment]
We will fix it soon. Thanks @tafelito !
